@host = http://localhost:3000/
@host1 = https://assignment5-reviewcode.herokuapp.com/
POST {{host}}login
Content-Type: application/json

{
    "email": "nhattan24121999@gmail.com",
    "password": "123456"
}

###
POST {{host}}signup
Content-Type: application/json

{
    "email": "nhattan24121999@gmail.com",
    "password": "123456",
    "confirmPassword": "123456"
}

###
GET {{host}}getUserInfo
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYThhMzZlM2I2NmViODk0ZDI4MmMyMSIsImlhdCI6MTYzODQ1ODg0MSwiZXhwIjoxNjM4NTQ1MjQxfQ.MNZ66HSsbT0rrazjmsCaJA4KVwM5-baQfS_b5vXCmAk


###
POST {{host}}forgotPassword
Content-Type: application/json

{
    "email": "nhattan24121999@gmail.com"
}

###
POST {{host}}resetPassword
Content-Type: application/json

{
    "otp": "F2B0A184",
    "password": "123456",
    "confirmPassword": "123456"
}
