@host = http://localhost:3000/
@host1 = https://assignment5-reviewcode.herokuapp.com/
POST {{host}}login
Content-Type: application/json

{
    "email": "nhattan24121999@gmail.com",
    "password": "12345678"
}

###
POST {{host}}signup
Content-Type: application/json

{
    "email": "tvnt22123@gmail.com",
    "password": "1234567",
    "confirmPassword": "1234567"
}

###
GET {{host}}getUserInfo
Authorization: eyJhbGciOiJI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYThmMGI2MmNiZTg1MDRmNzJkOWJlMSIsImlhdCI6MTYzODkzMjk1OCwiZXhwIjoxNjM5MDE5MzU4fQ.gCR97cMEVfWR1cX0VaLQCXT7Wr16MvDOfBklQsyxTd8


###
POST {{host}}forgotPassword
Content-Type: application/json

{
    "email": "tvnt221@gmail.com"
}

###
POST {{host}}resetPassword
Content-Type: application/json

{
    "otp": "02f629f3",
    "email": "tvnt221@gmail.com",
    "password": "12345678",
    "confirmPassword": "12345678"
}
