@host = http://localhost:3000/
@host1 = https://assignment5-reviewcode.herokuapp.com/
POST {{host}}login
Content-Type: application/json

{
    "email": "nhattan24121999@gmail.com",
    "password": "12345678"
}

###
POST {{host}}signup
Content-Type: application/json

{
    "email": "tvnt221@gmail.com",
    "password": "123456",
    "confirmPassword": "123456"
}

###
GET {{host}}getUserInfo
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCIdgkpXVCJ9.eyJpZCI6IjYxYThmMGI2MmNiZTg1MDRmNzJkOWJlMSIsImlhdCI6MTYzODg0MTE2OCwiZXhwIjoxNjM4OTI3NTY4fQ.ZwylFqV1STX1r6WRZnkkRJWP_95X9rHaGUs39wiBJqI


###
POST {{host}}forgotPassword
Content-Type: application/json

{
    "email": "tvnt221@gmail.com"
}

###
POST {{host}}resetPassword
Content-Type: application/json

{
    "otp": "1EE7BAD7",
    "email": "tvnt221@gmail.com",
    "password": "",
    "confirmPassword": ""
}
